version: "3"

services:
        mis-backend:
                build: backend/
                container_name: mis-backend
                volumes:
                        - "./backend/publish:/app"
                        - "./files:/files"
                        - "./logs:/logs"
                        - "/etc/localtime:/etc/localtime:ro"
                        - "/etc/timezone:/etc/timezone:ro"
                ports:
                        - 5001:80
                environment:
                        - ASPNETCORE_ENVIRONMENT=Production
                networks:
                        - default
                depends_on:
                        - database
        mis-frontend:
                image: nginx:stable-alpine
                container_name: mis-frontend
                volumes:
                        - "./frontend:/usr/share/nginx/html:Z"
                        - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
                        - "/etc/localtime:/etc/localtime:ro"
                        - "/etc/timezone:/etc/timezone:ro"
                ports:
                        - 80:80
                networks:
                        - default
                depends_on:
                        - mis-backend
        database:
                image: postgres:alpine
                container_name: database
                volumes:
                        - "./postgres:/var/lib/postgresql/data"
                ports:
                        - 5432:5432
                environment:
                        - POSTGRES_PASSWORD=1tsM1sP@sS
                networks:
                        - default